---
- name: proaluno
  hosts: teste
  become: yes

  vars:
    realm: "smbdomain.fflch.usp.br"
    
  tasks:
    - name: update
      apt:
        update_cache: yes

    - name: upgrade
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
        autoremove: yes

    - name: Corrige o timezone para America/Sao_Paulo
      include_role:
        name: adriagalin.timezone
      vars:
        ag_timezone: 'America/Sao_Paulo'

    - name: infOpen.locales
      include_role:
        name: infOpen.locales
      vars:
        locales_to_configure:
          - name: 'en_US.UTF-8'
            modifier: 'UTF-8'
          - name: 'pt_BR.UTF-8'
            modifier: 'UTF-8'
        locales_defaults:
          LANG: 'pt_BR.UTF-8'
          LC_CTYPE: 'pt_BR.UTF-8'
          LANGUAGE: 'pt_BR.UTF-8'

    - name: ontic.ntp
      include_role:
        name: ontic.ntp
      vars:
        ntp_timezone: 'America/Sao_Paulo'
        ntp_servers:
          - 143.107.72.180
          - 143.107.72.181
          - 143.107.72.182
          - 143.107.72.183

    - name: Configura resolv.conf para consultar DNSs no próprio samba
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers:
          - 143.107.72.180
          - 143.107.72.181
          - 143.107.72.182
          - 143.107.72.183
        resolv_conf_search_domains:
          - "{{ realm }}"

    - name: fflch.domain-member
      include_role:
        name: fflch.domain-member
      vars:
        domain_member_samba_server: sambadc180
        domain_member_interfaces: 'enp2s0 lo'
        domain_member_password: "{{ lookup('passwordstore', 'sti/servidores/smbdomain/Administrator/password') }}"

    - name: Install printers
      shell: "lpadmin -p {{ item.printer }} -v ipp://cups.fflch.usp.br:631/printers/{{ item.printer }} -m {{ item.model }} -o printer-error-policy=abort-job -o sides=two-sided-long-edge -E"
      with_items:
          - printer: adm_hp_pb_laserjet4250n_sti
            model: 'hplip:0/ppd/hplip/HP/hp-laserjet_4250-pcl3.ppd'

          - printer: adm_samsung_pb_k7500lx_fin
            value: 'openprinting-ppds:0/ppd/openprinting/Samsung/PS/Samsung_K7600_Series.ppd'

          - printer: adm_samsung_cor_x7500lx_ccint
            value: 'openprinting-ppds:0/ppd/openprinting/Samsung/PS/Samsung_X7600_Series.ppd Samsung X7600'

          - printer: adm_samsung_pb_m4080fx_sgerais
            value: 'openprinting-ppds:0/ppd/openprinting/Samsung/PS/Samsung_M408x_Series.ppd Samsung M408x'

          - printer: adm_samsung_pb_m4080fx_editora
            value: 'openprinting-ppds:0/ppd/openprinting/Samsung/PS/Samsung_M408x_Series.ppd Samsung M408x'


