---
- name: proaluno
  hosts: proaluno
  become: yes

  vars:
    smb_workgroup: smbdomain
    smb_realm: "smbdomain.fflch.usp.br"
    smb_dns_servers: 192.168.8.48
    smb_username: Administrator
    
  tasks:

    - name: update
      apt:
        update_cache: yes

    - name: upgrade
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
        autoremove: yes

    - name: Configura resolv.conf para consultar DNSs no próprio samba
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers:
          - 192.168.8.48
        resolv_conf_search_domains:
          - "{{ smb_realm }}"

    - name: Corrige o timezone para America/Sao_Paulo
      include_role:
        name: adriagalin.timezone
      vars:
        ag_timezone: 'America/Sao_Paulo'

    - name: infOpen.locales
      include_role:
        name: infOpen.locales
      vars:
        locales_to_configure:
          - name: 'en_US.UTF-8'
            modifier: 'UTF-8'
          - name: 'pt_BR.UTF-8'
            modifier: 'UTF-8'
        locales_defaults:
          LANG: 'pt_BR.UTF-8'
          LC_CTYPE: 'pt_BR.UTF-8'
          LANGUAGE: 'pt_BR.UTF-8'

    - name: ontic.ntp
      include_role:
        name: ontic.ntp
      vars:
        ntp_timezone: 'America/Sao_Paulo'
        ntp_servers:
          - '192.168.8.48'

    - name: fflch.domain-member
      include_role:
        name: fflch.domain-member
      vars:
        bind_password: "{{ lookup('passwordstore', 'sti/servidores/smbdomain/Administrator/password') }}"
