- name: fflch.domain-member
  src: https://github.com/fflch/ansible-role-domain-member.git
  version: master

- src: geerlingguy.firewall
- src: infOpen.locales
- src: ontic.ntp
- src: adriagalin.timezone
- src: blackstar257.resolv
- src: Stouts.hostname
