- name: fflch.sssd
  src: https://github.com/fflch/ansible-role-sssd.git
  version: master

- src: geerlingguy.firewall
- src: infOpen.locales
- src: ontic.ntp
- src: adriagalin.timezone
- src: blackstar257.resolv
