---
# tasks file for local.proaluno

- name: copy source.list
  template:
    src: "templates/sources.list.j2"
    dest: "/etc/apt/sources.list"

- name: update
  apt:
    update_cache: yes

- name: upgrade
  apt:
    upgrade: dist

- import_tasks: printers.yml
  when: proaluno_deploy_printers

- import_tasks: pacotes_debian.yml
  when: proaluno_install_pacotes_debian

- import_tasks: mate.yml
  when: proaluno_install_mate

- import_tasks: proaluno_init.yml
  when: proaluno_proaluno_init

- import_tasks: conky.yml
- import_tasks: lightdm.yml

- name: workaround - pam_mkhomedir.so umask=0077 não está rolando
  cron:
    name: "fix permissions"
    minute: "*/5"
    job: "chmod -R 0700 /home/*"



