- name: Instalação de pacotes mate
  apt:
    pkg:
      - task-mate-desktop
      - mate-desktop-environment
      - mate-menu
      - dconf-cli

- name: Remove screensaver - workaround
  apt:
    name: "mate-screensaver"
    state: absent
    purge: yes

- name: Remove screensaver - workaround
  apt:
    name: "mate-screensaver-common"
    state: absent
    purge: yes

- name: Copy /etc/skel/.config
  copy:
    src: files/mate/dot_config/
    dest: /etc/skel/.config
    mode: '0755'

- name: create /etc/skel/ folders
  file:
    path: "/etc/skel/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - 'Área de trabalho'
    - 'Documentos'
    - 'Downloads'
    - 'Imagens'
    - 'Vídeos'
    - 'Música'
    - 'Público'
    - 'Modelos'

- name: create /proaluno folder
  file:
    path: /proaluno
    state: directory
    mode: '0755'

- name: Copy /proaluno/login.sh
  copy:
    src: files/login.sh
    dest: /proaluno/login.sh
    mode: '0755'

- name: Copy /proaluno/dconf-dump.ini
  copy:
    src: files/dconf-dump.ini
    dest: /proaluno/dconf-dump.ini
    mode: '0755'

- name: Copy fflch.png
  copy:
    src: files/fflch.png
    dest: /proaluno/fflch.png
    mode: '0755'

- name: Copy 10dconf_override
  copy:
    src: files/10dconf_override
    dest: /etc/X11/Xsession.d/10dconf_override
    mode: '0644'

- name: Copy keyboard configuration
  copy:
    src: files/keyboard
    dest: /etc/default/keyboard
    mode: '0644'

- name: Copy welcome
  copy:
    src: files/welcome.sh
    dest: /proaluno/welcome.sh
    mode: '0755'

- name: Copy countdown.sh
  template:
    src: templates/countdown.sh
    dest: /proaluno/countdown.sh
    mode: '0755'
    
- name: Copy check_quotas.sh
  template:
    src: templates/check_quota.sh
    dest: /proaluno/check_quotas.sh
    mode: '0755'

- name: Copy quotas.desktop
  template:
    src: templates/quotas.desktop
    dest: '/etc/skel/Área de trabalho/quotas.desktop'
    mode: '0755'

- name: Copy login.sh
  copy:
    src: files/login.sh
    dest: /proaluno/login.sh
    mode: '0700'
