- name: Instalação de pacotes mate
  apt:
    pkg:
      - task-mate-desktop
      - mate-desktop-environment
      - mate-menu
      - dconf-cli

- name: Copy /etc/skel/.config
  copy:
    src: files/mate/dot_config/
    dest: /etc/skel/.config
    mode: '0755'

- name: create /etc/skel/ folders
  file:
    path: "/etc/skel/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - 'Área de trabalho'
    - 'Documentos'
    - 'Downloads'
    - 'Imagens'
    - 'Vídeos'
    - 'Música'
    - 'Público'
    - 'Modelos'

- name: create /proaluno folder
  file:
    path: /proaluno
    state: directory
    mode: '0755'

- name: Copy /proaluno/mate.sh
  copy:
    src: files/mate.sh
    dest: /proaluno/mate.sh
    mode: '0755'

- name: Copy /proaluno/dconf-dump.ini
  copy:
    src: files/dconf-dump.ini
    dest: /proaluno/dconf-dump.ini
    mode: '0755'

- name: Copy fflch.png
  copy:
    src: files/fflch.png
    dest: /proaluno/fflch.png
    mode: '0755'

- name: Copy 10dconf_override
  copy:
    src: files/10dconf_override
    dest: /etc/X11/Xsession.d/10dconf_override
    mode: '0644'

- name: Copy countdown.sh
  copy:
    src: files/countdown.sh
    dest: /proaluno/countdown.sh
    mode: '0755'

- name: create /etc/share/mate/autostart folder
  file:
    path: /etc/share/mate/autostart
    state: directory
    mode: '0755'

- name: Copy countdown.desktop
  copy:
    src: files/countdown.desktop
    dest: /etc/share/mate/autostart/countdown.desktop
    mode: '0755'
