- name: Copy limpa_homes.sh
  copy:
    src: files/limpa_homes.sh
    dest: /proaluno/limpa_homes.sh
    mode: '0700'

- name: proaluno_init.sh script
  cron:
    name: "a job for reboot"
    special_time: reboot
    job: "/proaluno/limpa_homes.sh"
