---
- name: laravel
  become: yes
  hosts: laravel

  vars:


  tasks:

    - import_tasks: ../partials/mariadb.yml
    - import_tasks: ../partials/php.yml

    # Essa task é só para o ambiente de dev
    - name: servidor de impressão dev
      lineinfile:
        path: /etc/hosts
        line: "192.168.7.203 quotas.proaluno.usp.br" 

    - name: servidor de impressão dev
      lineinfile:
        path: /etc/hosts
        line: "192.168.7.203 faker.proaluno.usp.br"  

    - name: faker.proaluno.usp.br
      include_role:
        name: fflch.deploy_laravel
      vars:
        deploy_laravel_generate_key: yes
        deploy_laravel_domain: "faker.proaluno.usp.br"
        deploy_laravel_repo: "https://github.com/uspdev/senhaunica-faker.git"
        deploy_laravel_repo_version: "master"
        deploy_laravel_env:
          - name: APP_NAME
            value: 'Faker'
          - name: APP_URL
            value: 'http://faker.proaluno.usp.br'
          - name: DB_USERNAME
            value: 'faker'
          - name: DB_PASSWORD
            value: "Pr0Aluno123"
          - name: DB_DATABASE
            value: 'faker'

    - name: quotas.proaluno.usp.br
      include_role:
        name: fflch.deploy_laravel
      vars:
        deploy_laravel_generate_key: yes
        deploy_laravel_domain: "quotas.proaluno.usp.br"
        deploy_laravel_repo: "https://github.com/fflch/quotas.git"
        deploy_laravel_repo_version: "master"
        deploy_laravel_env:
          - name: APP_NAME
            value: 'Quotas'
          - name: APP_URL
            value: 'http://quotas.proaluno.usp.br'
          - name: DB_USERNAME
            value: 'quotas'
          - name: DB_PASSWORD
            value: "Pr0Aluno123"
          - name: DB_DATABASE
            value: 'quotas'
          - name: SENHAUNICA_KEY
            value: "faker"
          - name: SENHAUNICA_SECRET
            value: "faker"
          - name: SENHAUNICA_DEV
            value: 'http://faker.proaluno.usp.br/wsusuario/oauth'
          - name: ADMINS
            value: '999'
