---
- name: samba
  become: yes
  hosts: samba

  vars:
    sambadc_realm: "proaluno.usp.br"
    ntp_dns_servers:
      - 192.168.7.202

  tasks:

    - import_tasks: ../partials/locale.yml
    - import_tasks: ../partials/install_samba.yml

    - name: configura /etc/hosts e /etc/hostnane
      include_role:
        name: Stouts.hostname
      vars:
        hostname_hostname: "{{ inventory_hostname }}.{{sambadc_realm}}"

    - name: Configura ntp
      include_role:
        name: geerlingguy.ntp
      vars:
        ntp_manage_config: true
        ntp_timezone: 'America/Sao_Paulo'
        ntp_servers:
          - 'a.st1.ntp.br'
          - 'b.st1.ntp.br' 
        ntp_restrict:
          - "127.0.0.1"
          - "::1"
          - "192.168.0.0 mask 255.255.0.0 nomodify notrap" 

    - name: Configura samba como um Domain Controller
      include_role:
        name: fflch.sambadc
      vars:
        sambadc_admin_password: "Pr0Aluno123"
 
    - name: Configura resolv.conf para consultar DNSs no próprio samba
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers: "{{ ntp_dns_servers }}"
        resolv_conf_search_domains:
          - "{{ sambadc_realm }}"
