---
- name: reboot
  hosts: letras
  become: yes

  vars:
    mensagem: "A sala pró-aluno fechará dentro de 5 minutos para manutenção"


  tasks:
    - name: registra usuário logado
      shell: >
        ls /home/ | grep -v vagrant
      register: logados_lista

    - set_fact:
        logado: "{{logados_lista.stdout_lines.0}}"

    - name: Aviso Template
      template:
        src: ../../roles/local.proaluno/templates/aviso.sh
        dest: '/proaluno/aviso.sh'
        mode: '0755'

    - name: mostra mensagem
      shell: "/proaluno/aviso.sh &"

