- name: Corrige o timezone para America/Sao_Paulo
  include_role:
    name: adriagalin.timezone
  vars:
    ag_timezone: 'America/Sao_Paulo'

- name: infOpen.locales
  include_role:
    name: infOpen.locales
  vars:
    locales_to_configure:
      - name: 'en_US.UTF-8'
        modifier: 'UTF-8'
      - name: 'pt_BR.UTF-8'
        modifier: 'UTF-8'
    locales_defaults:
      LANG: 'pt_BR.UTF-8'
      LC_CTYPE: 'pt_BR.UTF-8'
      LANGUAGE: 'pt_BR.UTF-8'

