- name: geerlingguy.ntp
  include_role:
    name: geerlingguy.ntp
  vars:
    ntp_timezone: 'America/Sao_Paulo'
    ntp_servers: "{{ ntp_dns_servers }}"

- name: Configura resolv.conf para consultar DNSs no próprio samba
  include_role:
    name: blackstar257.resolv
  vars:
    resolv_conf_nameservers: "{{ ntp_dns_servers }}"
    resolv_conf_search_domains:
      - "{{ sambadc_realm }}"