- name: install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: True
  vars:
    packages:
    - cups-tea4cups
    - php
    - php-cgi
    - php-mysql
    - python-dev
    - python-pip

- name: UNZIPPING pkpgcounter
  unarchive:
    src: "http://www.pykota.com/software/pkpgcounter/download/tarballs/pkpgcounter-3.50.tar.gz"
    dest: "/root"
    remote_src: yes

- name: Install Pillow python package for pkpgcounter
  pip:
    name: Pillow

- name: Install pkpgcounter
  shell: python setup.py install
  args:
    chdir: /root/pkpgcounter-3.50

- name: copy quota check
  template:
    src: '../../templates/quota_check.j2'
    dest: /root/quota_check
    mode: 0755

- name: copy quota save
  template:
    src: '../../templates/quota_save.j2'
    dest: '/root/quota_save'
    mode: 0755

- name: quota check
  lineinfile:
    path: '/etc/cups/tea4cups.conf'
    state: present
    create: yes
    line: 'prehook_quotacheck : /root/quota_check'

- name: quota save
  lineinfile:
    path: '/etc/cups/tea4cups.conf'
    state: present
    create: yes
    line: 'posthook_quotasave : /root/quota_save'
