---
- name: deploy vm example host
  hosts: vm
  become: yes

  vars:
    realm: "proaluno.usp.br"

  tasks:

    - name: proaluno role
      include_role:
        name: local.proaluno
      vars:
        proaluno_check_quota: "http://quotas.local.fflch.usp.br/"
        proaluno_install_pacotes_debian: False
        proaluno_update_keys: False
        proaluno_deploy_printers: True
        proaluno_install_mate: True
        proaluno_remove_all_printers: True
        proaluno_cups_server: "192.168.7.201:631"

        proaluno_printers:
          - name: pdfprinter
            device: "ipp://{{proaluno_cups_server}}/printers/pdfprinter"
            model: 'raw'

    - name: fflch.domain-member
      include_role:
        name: fflch.domain-member
      vars:
        domain_member_realm: "{{ realm }}"
        domain_member_samba_server: "samba"
        domain_member_password: "Pr0Aluno123"

    # Essa task é só para o ambiente de dev
    - name: servidor de impressão dev
      lineinfile:
        path: /etc/hosts
        line: "192.168.7.203 quotas.local.fflch.usp.br"  
