---
- name: deploy vm example host
  hosts: vm
  become: yes

  vars:
    proaluno_remove_all_printers: False
    realm: "proaluno.usp.br"
    cups_server: "ipp://192.168.8.43:631/printers"
    cups_printers:

      - name: frente_e_verso_borda_maior
        device: "{{cups_server}}/proaluno_letras_duplex"
        model: 'K7600_processado_duplex.ppd'

      - name: frente_e_verso_borda_menor
        device: "{{cups_server}}/proaluno_letras_duplex_borda_menor"
        model: 'K7600_processado_duplex_borda_menor.ppd'

      - name: somente_frente
        device: "{{cups_server}}/proaluno_letras_simplex"
        model: 'K7600_processado_simplex.ppd'

      - name: openprint
        device: "{{cups_server}}/let_samsung_pb_k7500lx_proaluno"
        model: 'openprinting-ppds:0/ppd/openprinting/Samsung/PS/Samsung_K7600_Series.ppd'

  tasks:

    - name: proaluno role
      include_role:
        name: local.proaluno
      vars:
        proaluno_check_quota: "http://quotas.local.fflch.usp.br/"
        proaluno_deploy_printers: True
        proaluno_install_pacotes_debian: False
        proaluno_install_mate: True
        proaluno_remove_all_printers: True
        proaluno_update_keys: False

    - name: Corrige o timezone para America/Sao_Paulo
      include_role:
        name: adriagalin.timezone
      vars:
        ag_timezone: 'America/Sao_Paulo'

    - name: infOpen.locales
      include_role:
        name: infOpen.locales
      vars:
        locales_to_configure:
          - name: 'en_US.UTF-8'
            modifier: 'UTF-8'
          - name: 'pt_BR.UTF-8'
            modifier: 'UTF-8'
        locales_defaults:
          LANG: 'pt_BR.UTF-8'
          LC_CTYPE: 'pt_BR.UTF-8'
          LANGUAGE: 'pt_BR.UTF-8'

    - name: geerlingguy.ntp
      include_role:
        name: geerlingguy.ntp
      vars:
        ntp_timezone: 'America/Sao_Paulo'
        ntp_servers:
          - 192.168.8.201

    - name: Configura resolv.conf para consultar DNSs no próprio samba
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers:
          - 192.168.8.201
        resolv_conf_search_domains:
          - "{{ realm }}"

    - name: fflch.domain-member
      include_role:
        name: fflch.domain-member
      vars:
        domain_member_realm: "{{ realm }}"
        domain_member_samba_server: "samba"
        domain_member_password: "Pr0Aluno123"

    - name: cmprescott.chrome
      include_role:
        name: cmprescott.chrome

    # Essa task é só para o ambiente de dev
    - name: servidor de impressão dev
      lineinfile:
        path: /etc/hosts
        line: "192.168.8.92 quotas.local.fflch.usp.br"  
