---
- name: deploy vm example host
  hosts: vm
  become: yes

  vars:
    realm: "proaluno.usp.br"

  tasks:
    - name: proaluno role
      include_role:
        name: local.proaluno
      vars:
        proaluno_deploy_printers: False
        proaluno_install_pacotes_debian: False
        proaluno_install_mate: True

    - name: Corrige o timezone para America/Sao_Paulo
      include_role:
        name: adriagalin.timezone
      vars:
        ag_timezone: 'America/Sao_Paulo'

    - name: infOpen.locales
      include_role:
        name: infOpen.locales
      vars:
        locales_to_configure:
          - name: 'en_US.UTF-8'
            modifier: 'UTF-8'
          - name: 'pt_BR.UTF-8'
            modifier: 'UTF-8'
        locales_defaults:
          LANG: 'pt_BR.UTF-8'
          LC_CTYPE: 'pt_BR.UTF-8'
          LANGUAGE: 'pt_BR.UTF-8'

    - name: geerlingguy.ntp
      include_role:
        name: geerlingguy.ntp
      vars:
        ntp_timezone: 'America/Sao_Paulo'
        ntp_servers:
          - 10.20.30.5

    - name: Configura resolv.conf para consultar DNSs no próprio samba
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers:
          - 10.20.30.5
        resolv_conf_search_domains:
          - "{{ realm }}"

    - name: fflch.domain-member
      include_role:
        name: fflch.domain-member
      vars:
        domain_member_realm: "{{ realm }}"
        domain_member_samba_server: "samba"
        domain_member_password: "Pr0Aluno123"

    - name: cmprescott.chrome
      include_role:
        name: cmprescott.chrome

