---
- name: tests
  hosts: tests
  become: yes

  vars:
    realm: "smbdomain.fflch.usp.br"
    cups_server: "ipp://cups.fflch.usp.br:631/printers/"
    cups_printers:
      - name: let_samsung_pb_k7500lx_proaluno
        short: letras
        model: 'openprinting-ppds:0/ppd/openprinting/Samsung/PS/Samsung_K7600_Series.ppd'

  tasks:

    - name: copy source.list
      template:
        src: "templates/sources.list.j2"
        dest: "/etc/apt/sources.list"

    - name: update
      apt:
        update_cache: yes
        cache_valid_time: 1800

    - name: upgrade
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
        autoremove: yes

    - name: Corrige o timezone para America/Sao_Paulo
      include_role:
        name: adriagalin.timezone
      vars:
        ag_timezone: 'America/Sao_Paulo'

    - name: infOpen.locales
      include_role:
        name: infOpen.locales
      vars:
        locales_to_configure:
          - name: 'en_US.UTF-8'
            modifier: 'UTF-8'
          - name: 'pt_BR.UTF-8'
            modifier: 'UTF-8'
        locales_defaults:
          LANG: 'pt_BR.UTF-8'
          LC_CTYPE: 'pt_BR.UTF-8'
          LANGUAGE: 'pt_BR.UTF-8'

    - name: geerlingguy.ntp
      include_role:
        name: geerlingguy.ntp
      vars:
        ntp_timezone: 'America/Sao_Paulo'
        ntp_servers:
          - 143.107.72.180
          - 143.107.72.181
          - 143.107.72.182
          - 143.107.72.183

    - name: Configura resolv.conf para consultar DNSs no próprio samba
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers:
          - 143.107.72.180
          - 143.107.72.181
          - 143.107.72.182
          - 143.107.72.183
        resolv_conf_search_domains:
          - "{{ realm }}"

    - name: fflch.domain-member
      include_role:
        name: fflch.domain-member
      vars:
        domain_member_samba_server: sambadc180
        domain_member_password: "{{ lookup('passwordstore', 'sti/servidores/smbdomain/Administrator/password') }}"

    # https://wiki.debian.org/SystemPrinting
    - name: Install a printers list of packages
      apt:
        pkg:
        - cups
        - task-print-server
        - printer-driver-all
        - foomatic-db-engine
        - hp-ppd
        - openprinting-ppds

    - name: Install printers
      shell: >
        lpadmin -p {{ item.short }}
        -v {{cups_server}}{{ item.name }}
        -m {{ item.model }}
        -o printer-error-policy=abort-job
        -o sides=two-sided-long-edge -E
      with_items: "{{ cups_printers }}"

    - name: Disable cups-browsed
      systemd:
        name: "cups-browsed"
        state: stopped
        enabled: no
        masked: yes

    - name: Remove avahi-daemon - para não varrer impressoras na rede
      apt:
        name: "avahi-daemon"
        purge: yes

    - name: Instalação de pacotes via apt
      apt:
        pkg:
          - terminator
          - vlc
          - build-essential
          - firmware-linux-nonfree
          - chromium
          - okular
          - nomacs
          - praat
          - qgis
          - vim
          - r-base
          - gfortran
          - fonts-crosextra-carlito
          - fonts-crosextra-caladea
          - ttf-mscorefonts-installer
          - gimp
          - gimp-help-pt
          - inkscape
          - audacity
          - git
          - gvfs-backends # para celulares
          - gnome-disk-utility
          - zip
          - unzip
          - rar
          - unrar
